"""
A simple AI Action to validate LLMs answers.

"""

from robocorp.actions import action
import anthropic

@action(is_consequential=False)
def validate(user_question: str, proposed_answer: str) -> str:
    """
    Validates LLMs proposed answers with a second source.

    Args:
        user_question (str): User's original question
        proposed_answer (str): What the LLM is proposing the answer should be

    Returns:
        str: Suggested modifications to the proposed answer
    """

    client = anthropic.Anthropic(
        api_key="EDIT_THIS",
    )

    message = client.messages.create(
        model="claude-3-opus-20240229",
        max_tokens=2000,
        temperature=0,
        system="Your task is to validate the answer generated by another system. Look at the user's original question, and the proposed answer. Use your own knowledge to propose improvements to the answer. Give a list of improvement suggestions, and explain why you think they should be made.",
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": f"How would you improve the answer below that an other system has generated to a following question:\n\nUSER QUESTION:\n{user_question}\n\nPROPOSED ANSWER:\n{proposed_answer}.\n\nInstructions:\n- If the original question contains detailed instructions on the style or format of the response, you only can suggest improvements that conform with those.\n- Do not suggest improvements on minor details, if the original answer is correct. For example, do not fix comma typos."
                    }
                ]
            }
        ]
    )
    # print(message.content)

    return message.content[0].text
