
# Required: A short name for the action package
name: PostgreSQL Universal Actions
    
# Required: A description of what's in the action package.
description: This example simplifies interactions with PostgreSQL databases by allowing users to perform queries through conversational inputs translated by Large Language Models (LLMs), like OpenAI's GPT

# Required: The current version of this action package.
version: 0.0.1

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/blob/master/example-postgres-universal/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - robocorp=1.6.2
  - robocorp-actions=0.0.7
  - psycopg2-binary=2.9.9

