name: Secret Greeter

description: Greets user with a secret message

documentation: https://github.com/robocorp/robocorp/blob/master/action_server/docs/guides/07-secrets.md

dependencies:
  conda-forge:
    - python=3.10.12
    - uv=0.1.37
  pypi:
    - sema4ai-actions=0.5.0
