# Required: A short name for the action package
name: Google Sheets Actions

# Required: A description of what's in the action package.
description: Reads the spreadsheet metadata and sheet contents, creates sheets and adds rows.

# Required: The current version of this action package.
version: 0.0.1

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/blob/master/google-sheets/README.md


dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - robocorp=1.6.2
  - robocorp-actions=0.0.9
  - rpaframework-google=9.0.0
  - pydantic=2.6.4
  - gspread=6.0.2

