
# Required: A short name for the action package
name: API and Slack notify example
    
# Required: A description of what's in the action package.
description: Example contains 2 actions demostrating the use of APIs and Slack
# Required: The current version of this action package.
version: 0.0.1

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/tree/master/api-and-notify/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - robocorp=1.6.2
  - robocorp-actions=0.0.7
  - rpaframework=28.3.0

