
# Required: A short name for the action package
name: Comparing timezones
    
# Required: A description of what's in the action package.
description: Compares user timezone time difference to given timezones

# Required: The current version of this action package.
version: 0.0.1

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/blob/master/deploy-docker/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - robocorp=1.6.2
  - robocorp-actions=0.0.7
  - pytz=2024.1

