
# Required: A short name for the action package
name: gmail-smtp

# Required: A description of what's in the action package.
description: Send an email with Google SMTP using app password for auth

# Required: The current version of this action package.
version: 0.0.1

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - robocorp=1.6.2
  - robocorp-actions=0.0.9
  - pytz=2024.1
  - rpaframework=28.3.0

