
# Required: A short name for the action package
name: Greeter example

# Required: A description of what's in the action package.
description: This shows the very basic python action in action

# Required: The current version of this action package.
version: 0.0.2

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/blob/master/greeter/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - robocorp=2.0.0
  - robocorp-actions=0.1.0
  - requests=2.31.0
