
# Required: A short name for the action package
name: Analyze Large JSON data
    
# Required: A description of what's in the action package.
description: This package provides a set of actions tailored for fetching and analyzing large JSON data directly from internet sources.

# Required: The current version of this action package.
version: 0.0.1

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/blob/master/example-curly-json/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - robocorp=1.6.2
  - robocorp-actions=0.0.7
  - requests=2.31.0
  - jmespath=1.0.1

