name: Get random joke

description: This simple example shows how to make API calls with Actions.

documentation: https://github.com/robocorp/actions-cookbook/tree/master/api-jokes/README.md

dependencies:
  conda-forge:
    - python=3.10.12
    - uv=0.1.37
  pypi:
  - sema4ai-actions=0.5.0
  - requests=2.31.0

